### ISSUE TITLE
TestProperties.java parses properties for each method invocation

### ISSUE THREAD

**Issue by RnSn** [vasylboliuk/googleAutomation#1]
``` java
readProperties();
```

is called for every invocation of other public methods.

``` java
public static String getGooglePageUrl() {
        readProperties();

public static int getWaiterTimeout() {
        readProperties();
```

There must be a better way.

``` java
public static void readProperties()
```

probably should not be `public`, but `private`

`readProperties()` should use `Class.getResourceAsStream()` to load properties in case the code is packaged in a jar.

And last but not least, `readProperties()` should check if `props` are already populated.

``` java
readProperties() {
   if (props != null) {
       return;
   }
```

**Comment by vasylboliuk** [comment]
Thanks Roman for your comments. Issue has already fixed.

**Comment by RnSn** [comment]
There are still couple of improvements that can be done.
First, make `static Properties props;` `private`.
Second, remove `static FileInputStream in;` as you are not using it.
Third, refactor `readProperties()` to use **try-with-resources**.
Fourth, remove commented code.
Fifth, don't just print stack trace, re-throw a runtime exception, as your program cannot function correctly without those properties.
Example, 

``` java
} catch (IOException e) {
    throw new UncheckedIOException(e);
}
```

**Comment by vasylboliuk** [comment]
Added all fixes and for last comment I changed  to next block of code(Java7):

```
} catch (Exception e) {
    throw new RuntimeException(e);
    }
```
